# Generated by Django 5.2.10 on 2026-01-28 15:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Категория деятельности',
                'verbose_name_plural': 'Категории деятельности',
                'db_table': 'activity_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('template_type', models.CharField(choices=[('global', 'Глобальный'), ('local', 'Локальный')], default='global', max_length=10, verbose_name='Тип шаблона')),
                ('version', models.IntegerField(default=1, verbose_name='Версия')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_by_id', models.IntegerField(blank=True, null=True, verbose_name='Создан (ID)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_by_id', models.IntegerField(blank=True, null=True, verbose_name='Обновлён (ID)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('activity_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='task_templates.activitycategory', verbose_name='Категория деятельности')),
                ('based_on_global', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_variants', to='task_templates.tasktemplate', verbose_name='Основан на глобальном')),
            ],
            options={
                'verbose_name': 'Шаблон задачи',
                'verbose_name_plural': 'Шаблоны задач',
                'db_table': 'task_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskTemplateStage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('estimated_duration_hours', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.5)], verbose_name='Предполагаемая длительность (часы)')),
                ('sequence_number', models.IntegerField(verbose_name='Номер последовательности')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='task_templates.tasktemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Этап шаблона задачи',
                'verbose_name_plural': 'Этапы шаблонов задач',
                'db_table': 'task_template_stages',
                'ordering': ['template', 'sequence_number'],
            },
        ),
        migrations.CreateModel(
            name='TemplateFilterPreference',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(unique=True, verbose_name='Пользователь (ID)')),
                ('show_all_categories', models.BooleanField(default=False, verbose_name='Показывать все категории')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('last_category_filter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='task_templates.activitycategory', verbose_name='Последний фильтр категории')),
            ],
            options={
                'verbose_name': 'Предпочтение фильтра шаблонов',
                'verbose_name_plural': 'Предпочтения фильтров шаблонов',
                'db_table': 'template_filter_preferences',
            },
        ),
        migrations.CreateModel(
            name='TemplateProposal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('proposed_by_id', models.IntegerField(blank=True, null=True, verbose_name='Предложено (ID)')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Причина отклонения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('reviewed_by_id', models.IntegerField(blank=True, null=True, verbose_name='Рассмотрено (ID)')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата рассмотрения')),
                ('approved_global_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_from_proposal', to='task_templates.tasktemplate', verbose_name='Одобренный глобальный шаблон')),
                ('local_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='task_templates.tasktemplate', verbose_name='Локальный шаблон')),
            ],
            options={
                'verbose_name': 'Предложение шаблона',
                'verbose_name_plural': 'Предложения шаблонов',
                'db_table': 'template_proposals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateAuditLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Создание'), ('update', 'Обновление'), ('delete', 'Удаление'), ('approve_proposal', 'Одобрение предложения'), ('reject_proposal', 'Отклонение предложения')], max_length=20, verbose_name='Действие')),
                ('performed_by_id', models.IntegerField(blank=True, null=True, verbose_name='Выполнено (ID)')),
                ('changes', models.JSONField(default=dict, verbose_name='Изменения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='task_templates.tasktemplate', verbose_name='Шаблон')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='task_templates.templateproposal', verbose_name='Предложение')),
            ],
            options={
                'verbose_name': 'Журнал аудита шаблонов',
                'verbose_name_plural': 'Журналы аудита шаблонов',
                'db_table': 'template_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tasktemplate',
            index=models.Index(fields=['template_type', 'is_active'], name='task_templa_templat_2d8c64_idx'),
        ),
        migrations.AddIndex(
            model_name='tasktemplate',
            index=models.Index(fields=['activity_category', 'is_active'], name='task_templa_activit_e31bdf_idx'),
        ),
        migrations.AddIndex(
            model_name='tasktemplatestage',
            index=models.Index(fields=['template', 'sequence_number'], name='task_templa_templat_37d30d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tasktemplatestage',
            unique_together={('template', 'sequence_number')},
        ),
        migrations.AddIndex(
            model_name='templateproposal',
            index=models.Index(fields=['status', 'created_at'], name='template_pr_status_1a5713_idx'),
        ),
        migrations.AddIndex(
            model_name='templateproposal',
            index=models.Index(fields=['proposed_by_id', 'status'], name='template_pr_propose_99641e_idx'),
        ),
        migrations.AddIndex(
            model_name='templateauditlog',
            index=models.Index(fields=['template', 'created_at'], name='template_au_templat_5e3931_idx'),
        ),
        migrations.AddIndex(
            model_name='templateauditlog',
            index=models.Index(fields=['action', 'created_at'], name='template_au_action_c39ae3_idx'),
        ),
    ]
