# Generated by Django 5.2.10 on 2026-01-28 14:23

from django.db import migrations


def add_categories(apps, schema_editor):
    """Добавить предопределённые категории деятельности"""
    ActivityCategory = apps.get_model('task_templates', 'ActivityCategory')
    
    categories = [
        {
            'name': 'Логистика',
            'slug': 'logistics',
            'description': 'Управление логистикой и доставкой товаров'
        },
        {
            'name': 'Доставка',
            'slug': 'delivery',
            'description': 'Процессы доставки и распределения'
        },
        {
            'name': 'Автосервис',
            'slug': 'auto-service',
            'description': 'Обслуживание и ремонт автомобилей'
        },
        {
            'name': 'Атомная энергетика',
            'slug': 'nuclear-energy',
            'description': 'Операции в атомной энергетике'
        },
        {
            'name': 'Горнорудное предприятие',
            'slug': 'mining',
            'description': 'Горнодобывающие операции'
        },
        {
            'name': 'Обслуживание техники',
            'slug': 'equipment-maintenance',
            'description': 'Техническое обслуживание оборудования'
        },
    ]
    
    for category_data in categories:
        ActivityCategory.objects.get_or_create(
            slug=category_data['slug'],
            defaults={
                'name': category_data['name'],
                'description': category_data['description'],
                'is_active': True,
            }
        )


class Migration(migrations.Migration):

    dependencies = [
        ('task_templates', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_categories),
    ]
