# Generated by Django 5.2.10 on 2026-01-28 17:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_templates', '0002_add_predefined_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Код материала')),
                ('unit', models.CharField(default='шт', max_length=50, verbose_name='Единица измерения')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость за единицу')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
                'db_table': 'materials',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StageMaterial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Количество')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stage_usages', to='task_templates.material', verbose_name='Материал')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='task_templates.tasktemplatestage', verbose_name='Этап')),
            ],
            options={
                'verbose_name': 'Материал этапа',
                'verbose_name_plural': 'Материалы этапов',
                'db_table': 'stage_materials',
                'ordering': ['stage', 'material'],
                'unique_together': {('stage', 'material')},
            },
        ),
    ]
