# Generated by Django 5.2.10 on 2026-01-28 18:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_templates', '0003_material_stagematerial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DurationUnit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_type', models.CharField(choices=[('hour', 'Час'), ('minute', 'Минута'), ('second', 'Секунда')], max_length=10, unique=True, verbose_name='Тип')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('abbreviation', models.CharField(max_length=5, verbose_name='Сокращение')),
            ],
            options={
                'verbose_name': 'Единица времени',
                'verbose_name_plural': 'Единицы времени',
                'db_table': 'duration_units',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('abbreviation', models.CharField(max_length=10, unique=True, verbose_name='Сокращение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Единица измерения',
                'verbose_name_plural': 'Единицы измерения',
                'db_table': 'units_of_measure',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='tasktemplatestage',
            name='estimated_duration_hours',
        ),
        migrations.AddField(
            model_name='tasktemplatestage',
            name='estimated_duration',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Предполагаемая длительность'),
        ),
        migrations.AddField(
            model_name='tasktemplatestage',
            name='duration_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='task_templates.durationunit', verbose_name='Единица времени'),
        ),
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='task_templates.unitofmeasure', verbose_name='Единица измерения'),
        ),
    ]
