# Generated by Django 5.2.10 on 2026-01-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_templates', '0004_durationunit_unitofmeasure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='durationunit',
            name='unit_type',
            field=models.CharField(choices=[('second', 'Секунда'), ('minute', 'Минута'), ('hour', 'Час'), ('day', 'День'), ('year', 'Год')], max_length=10, unique=True, verbose_name='Тип'),
        ),
    ]
