# Generated by Django 5.2.10 on 2026-01-28 22:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_templates', '0011_add_leads_to_stop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktemplatestage',
            name='duration_from',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Длительность от'),
        ),
        migrations.AlterField(
            model_name='tasktemplatestage',
            name='duration_to',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Длительность до'),
        ),
    ]
