# Generated by Django 5.2.10 on 2026-01-29 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_templates', '0012_alter_tasktemplatestage_duration_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktemplate',
            name='diagram_svg',
            field=models.TextField(blank=True, null=True, verbose_name='SVG диаграмма'),
        ),
    ]
