# Generated by Django 5.2.10 on 2026-02-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_templates', '0013_tasktemplate_diagram_svg'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktemplate',
            name='n8n_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Данные процесса (n8n)'),
        ),
    ]
