# Generated by Django 5.2.10 on 2026-02-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_templates', '0014_tasktemplate_n8n_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktemplate',
            name='diagram_layout',
            field=models.JSONField(blank=True, default=dict, verbose_name='Layout диаграммы'),
        ),
    ]
