# Generated by Django 5.2.10 on 2026-02-02 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_templates', '0015_tasktemplate_diagram_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktemplatestage',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Описание'),
        ),
    ]
