# Generated by Django 5.2.9 on 2026-01-06 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0004_tenantuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
