# Generated by Django 5.2.9 on 2026-01-07 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_client_contact_person_client_email_and_more'),
        ('users_app', '0005_tenantuser_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admins', to='customers.client', verbose_name='Предприятие'),
        ),
    ]
