# Generated by Django 5.2.9 on 2026-01-08 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0007_tenantuser_phone_department_tenantuser_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantuser',
            name='position',
            field=models.CharField(blank=True, max_length=255, verbose_name='Должность'),
        ),
    ]
