# Generated by Django 5.2.9 on 2026-01-08 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0009_position_alter_tenantuser_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantuser',
            name='can_delete_media',
            field=models.BooleanField(default=False, verbose_name='Может удалять медиа'),
        ),
    ]
