# Generated by Django 5.2.9 on 2026-01-08 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0010_tenantuser_can_delete_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantuser',
            name='can_delete_media',
        ),
    ]
