# Generated by Django 5.2.10 on 2026-01-30 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPasswordLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_username', models.CharField(max_length=150, verbose_name='Логин сотрудника')),
                ('action', models.CharField(choices=[('generated', 'Сгенерирован'), ('reset', 'Сброшен'), ('viewed', 'Просмотрен')], default='generated', max_length=20, verbose_name='Действие')),
                ('password_length', models.IntegerField(default=16, verbose_name='Длина пароля')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Администратор')),
            ],
            options={
                'verbose_name': 'Лог генерации пароля',
                'verbose_name_plural': 'Логи генерации паролей',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='dashboard_a_timesta_c67ae8_idx'), models.Index(fields=['employee_username'], name='dashboard_a_employe_fe8cea_idx'), models.Index(fields=['admin_user'], name='dashboard_a_admin_u_67990b_idx')],
            },
        ),
    ]
