# Generated by Django 5.2.10 on 2026-01-30 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adminpasswordlog',
            name='admin_username',
            field=models.CharField(default='unknown', max_length=150, verbose_name='Имя администратора'),
        ),
        migrations.AlterField(
            model_name='adminpasswordlog',
            name='admin_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Администратор (Django User)'),
        ),
        migrations.AddIndex(
            model_name='adminpasswordlog',
            index=models.Index(fields=['admin_username'], name='dashboard_a_admin_u_53702b_idx'),
        ),
    ]
