# Generated by Django 5.2.10 on 2026-01-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_adminpasswordlog_admin_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpasswordlog',
            name='action',
            field=models.CharField(choices=[('generated', 'Сгенерирован'), ('reset', 'Сброшен'), ('viewed', 'Просмотрен'), ('deleted', 'Удален')], default='generated', max_length=20, verbose_name='Действие'),
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_username', models.CharField(max_length=150, verbose_name='Администратор')),
                ('task_title', models.CharField(max_length=200, verbose_name='Название задачи')),
                ('task_id', models.IntegerField(blank=True, null=True, verbose_name='ID задачи')),
                ('action', models.CharField(choices=[('created', 'Создана'), ('updated', 'Обновлена'), ('deleted', 'Удалена'), ('bulk_deleted', 'Массовое удаление'), ('cleared', 'Очищены все')], max_length=20, verbose_name='Действие')),
                ('count', models.IntegerField(default=1, verbose_name='Количество задач')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
            ],
            options={
                'verbose_name': 'Лог операции с задачей',
                'verbose_name_plural': 'Логи операций с задачами',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='dashboard_t_timesta_a477c7_idx'), models.Index(fields=['task_id'], name='dashboard_t_task_id_c0d0e9_idx'), models.Index(fields=['admin_username'], name='dashboard_t_admin_u_b3215f_idx'), models.Index(fields=['action'], name='dashboard_t_action_770603_idx')],
            },
        ),
    ]
