# Generated by Django 5.2.10 on 2026-02-02 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_adminpasswordlog_action_tasklog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklog',
            name='action',
            field=models.CharField(choices=[('created', 'Создана'), ('updated', 'Обновлена'), ('deleted', 'Удалена'), ('bulk_deleted', 'Массовое удаление'), ('cleared', 'Очищены все'), ('status_changed', 'Изменен статус')], max_length=20, verbose_name='Действие'),
        ),
    ]
