"""

Django settings for config project.



Generated by 'django-admin startproject' using Django 5.2.9.



For more information on this file, see

https://docs.djangoproject.com/en/5.2/topics/settings/



For the full list of settings and their values, see

https://docs.djangoproject.com/en/5.2/ref/settings/

"""



from pathlib import Path

import os

from decouple import config



# Build paths inside the project like this: BASE_DIR / 'subdir'.

BASE_DIR = Path(__file__).resolve().parent.parent





# Quick-start development settings - unsuitable for production

# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/



# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = 'django-insecure-r9yxrys@9fc57$fu99@^rl!$i$wyi$e_5w#5@ddc@-$0@bfbwc'



# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = True



ALLOWED_HOSTS = ['*', 'qtrace.ru', '.qtrace.ru', 'localhost', '127.0.0.1', '192.168.1.220', 'lvh.me', '.lvh.me', '.localhost']





# Application definition



# Shared apps (public schema)

SHARED_APPS = [

    'django_tenants',

    'django.contrib.admin',

    'django.contrib.auth',

    'django.contrib.contenttypes',

    'django.contrib.sessions',

    'django.contrib.messages',

    'django.contrib.staticfiles',

    'django.contrib.humanize',

    'customers',

    'ai_app',

]



# Tenant-specific apps

TENANT_APPS = [

    'rest_framework',

    'rest_framework_simplejwt',

    'djoser',

    'tasks',

    'media_app',

    'dashboard',

    'users_app',

]



INSTALLED_APPS = SHARED_APPS + TENANT_APPS



MIDDLEWARE = [

    'django_tenants.middleware.main.TenantMainMiddleware',

    'customers.middleware.TenantStatusMiddleware',

    'django.middleware.security.SecurityMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]



ROOT_URLCONF = 'config.urls'

PUBLIC_SCHEMA_URLCONF = 'config.urls'

TENANT_URLCONF = 'config.tenant_urls'



TEMPLATES = [

    {

        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        'DIRS': [],

        'APP_DIRS': True,

        'OPTIONS': {

            'context_processors': [

                'django.template.context_processors.request',

                'django.contrib.auth.context_processors.auth',

                'django.contrib.messages.context_processors.messages',

            ],

        },

    },

]



WSGI_APPLICATION = 'config.wsgi.application'





# Database

# https://docs.djangoproject.com/en/5.2/ref/settings/#databases



DATABASES = {

    'default': {

        'ENGINE': 'django_tenants.postgresql_backend',

        'NAME': config('DB_NAME', default='skkp_db'),

        'USER': config('DB_USER', default='postgres'),

        'PASSWORD': config('DB_PASSWORD', default='postgres'),

        'HOST': config('DB_HOST', default='localhost'),

        'PORT': config('DB_PORT', default='5432'),

    }

}



DATABASE_ROUTERS = ('django_tenants.routers.TenantSyncRouter',)





# Password validation

# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators



AUTH_PASSWORD_VALIDATORS = [

    {

        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',

    },

    {

        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',

    },

    {

        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',

    },

    {

        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',

    },

]





# Internationalization

# https://docs.djangoproject.com/en/5.2/topics/i18n/



LANGUAGE_CODE = 'ru'



TIME_ZONE = 'UTC'



USE_I18N = True



USE_TZ = True



USE_THOUSAND_SEPARATOR = True

THOUSAND_SEPARATOR = ' '

NUMBER_GROUPING = 3





# Tenant settings

SHOW_PUBLIC_IF_NO_TENANT_FOUND = True



# Static files (CSS, JavaScript, Images)

# https://docs.djangoproject.com/en/5.2/howto/static-files/



STATIC_URL = 'static/'

STATICFILES_DIRS = [

    BASE_DIR / 'static',

]

STATIC_ROOT = BASE_DIR / 'staticfiles'



# Media files

MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR



# Django-tenants media settings

MULTITENANT_RELATIVE_MEDIA_ROOT = "" # Files will be stored in MEDIA_ROOT/tenant_schema/

DEFAULT_FILE_STORAGE = 'django_tenants.storage.TenantFileSystemStorage'



# Login settings

LOGIN_URL = '/login/'

LOGIN_REDIRECT_URL = '/'

LOGOUT_REDIRECT_URL = '/login/'



# Default primary key field type

# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field



DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# Authentication backends

AUTHENTICATION_BACKENDS = [

    'users_app.backends.TenantUserBackend',

    'django.contrib.auth.backends.ModelBackend',

]



# Django-tenants settings

TENANT_MODEL = 'customers.Client'

TENANT_DOMAIN_MODEL = 'customers.Domain'

SHOW_PUBLIC_IF_NO_TENANT_FOUND = True



# REST Framework settings

REST_FRAMEWORK = {

    'DEFAULT_AUTHENTICATION_CLASSES': (

        'users_app.authentication.TenantJWTAuthentication',

        'rest_framework.authentication.SessionAuthentication',

    ),

    'DEFAULT_PERMISSION_CLASSES': (

        'rest_framework.permissions.IsAuthenticated',

    ),

}



# JWT settings

from datetime import timedelta



SIMPLE_JWT = {

    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),

    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),

    'ALGORITHM': 'HS256',

    'SIGNING_KEY': SECRET_KEY,

}



