# Generated by Django 5.2.9 on 2026-01-05 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='schema_name',
        ),
    ]
