# Generated by Django 5.2.9 on 2026-01-07 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_client_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='client',
            name='subscription_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Срок подписки'),
        ),
        migrations.AddField(
            model_name='client',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
    ]
