# Generated by Django 5.2.9 on 2026-01-07 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_client_contact_person_client_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название тарифа')),
                ('price_month', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена в месяц')),
                ('price_year', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена в год')),
                ('max_users', models.PositiveIntegerField(default=3, verbose_name='Макс. пользователей')),
                ('storage_gb', models.PositiveIntegerField(default=100, verbose_name='Объем хранилища (ГБ)')),
                ('work_days_limit', models.PositiveIntegerField(default=10, verbose_name='Дней работы/хранения')),
                ('has_mobile_app', models.BooleanField(default=True, verbose_name='Мобильное приложение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Тарифный план',
                'verbose_name_plural': 'Тарифные планы',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='customers.subscriptionplan', verbose_name='Тарифный план'),
        ),
    ]
