# Generated by Django 5.2.9 on 2026-01-07 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(default='smtp.gmail.com', max_length=255, verbose_name='SMTP сервер')),
                ('email_port', models.PositiveIntegerField(default=587, verbose_name='Порт')),
                ('email_host_user', models.CharField(blank=True, max_length=255, verbose_name='Пользователь (Email)')),
                ('email_host_password', models.CharField(blank=True, max_length=255, verbose_name='Пароль')),
                ('email_use_tls', models.BooleanField(default=True, verbose_name='Использовать TLS')),
                ('email_use_ssl', models.BooleanField(default=False, verbose_name='Использовать SSL')),
                ('default_from_email', models.EmailField(blank=True, max_length=254, verbose_name='Email отправителя по умолчанию')),
            ],
            options={
                'verbose_name': 'Настройки почты',
                'verbose_name_plural': 'Настройки почты',
            },
        ),
    ]
