# Generated by Django 5.2.9 on 2026-01-07 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
    ]
