# Generated by Django 5.2.9 on 2026-01-08 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='can_admin_delete_media',
            field=models.BooleanField(default=True, verbose_name='Админ может удалять медиа'),
        ),
    ]
