# Generated by Django 5.2.9 on 2026-01-08 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0015_client_can_admin_delete_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='customers.client'),
        ),
    ]
