# Generated by Django 5.2.9 on 2026-01-08 02:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0016_userprofile_tenant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={},
        ),
        migrations.RemoveField(
            model_name='client',
            name='telegram',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='error_log',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='is_sent',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='user_agent',
        ),
        migrations.RemoveField(
            model_name='mailsettings',
            name='default_from_email',
        ),
        migrations.RemoveField(
            model_name='mailsettings',
            name='email_host',
        ),
        migrations.RemoveField(
            model_name='mailsettings',
            name='email_host_password',
        ),
        migrations.RemoveField(
            model_name='mailsettings',
            name='email_host_user',
        ),
        migrations.RemoveField(
            model_name='mailsettings',
            name='email_port',
        ),
        migrations.RemoveField(
            model_name='mailsettings',
            name='email_use_ssl',
        ),
        migrations.RemoveField(
            model_name='mailsettings',
            name='email_use_tls',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='client',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='has_mobile_app',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='storage_gb',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='work_days_limit',
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mailsettings',
            name='password',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mailsettings',
            name='port',
            field=models.IntegerField(default=587),
        ),
        migrations.AddField(
            model_name='mailsettings',
            name='sender_email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='mailsettings',
            name='server',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mailsettings',
            name='use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mailsettings',
            name='user',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='customers.client'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_storage_gb',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_delete_media',
            field=models.BooleanField(default=False, verbose_name='Разрешить удаление файлов'),
        ),
        migrations.AlterField(
            model_name='client',
            name='can_admin_delete_media',
            field=models.BooleanField(default=False, verbose_name='Разрешить админу удалять медиа'),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='subscription_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_users',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price_month',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price_year',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
