# Generated by Django 5.2.9 on 2026-01-08 16:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0017_alter_contactmessage_options_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='max_storage_gb',
            new_name='storage_gb',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_mobile_app',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='work_days_limit',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
