# Generated by Django 5.2.9 on 2026-01-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0019_alter_client_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailsettings',
            old_name='sender_email',
            new_name='default_from_email',
        ),
        migrations.RenameField(
            model_name='mailsettings',
            old_name='password',
            new_name='email_host',
        ),
        migrations.RenameField(
            model_name='mailsettings',
            old_name='server',
            new_name='email_host_password',
        ),
        migrations.RenameField(
            model_name='mailsettings',
            old_name='user',
            new_name='email_host_user',
        ),
        migrations.RenameField(
            model_name='mailsettings',
            old_name='port',
            new_name='email_port',
        ),
        migrations.RenameField(
            model_name='mailsettings',
            old_name='use_tls',
            new_name='email_use_tls',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='error_log',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='user_agent',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mailsettings',
            name='email_use_ssl',
            field=models.BooleanField(default=False),
        ),
    ]
