# Generated by Django 5.2.9 on 2026-01-09 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0020_rename_sender_email_mailsettings_default_from_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
