# Generated by Django 5.2.9 on 2026-01-09 23:26

from django.db import migrations, connection

def migrate_user_profiles(apps, schema_editor):
    if schema_editor.connection.schema_name != 'public':
        return

    # Check if old table exists
    with connection.cursor() as cursor:
        cursor.execute("SELECT tablename FROM pg_catalog.pg_tables WHERE schemaname = 'public' AND tablename = 'users_app_userprofile';")
        if not cursor.fetchone():
            return

    User = apps.get_model('auth', 'User')
    NewProfile = apps.get_model('customers', 'UserProfile')
    
    with connection.cursor() as cursor:
        cursor.execute("SELECT user_id, role, tenant_id FROM users_app_userprofile")
        for user_id, role, tenant_id in cursor.fetchall():
            # Check if user exists
            if not User.objects.filter(id=user_id).exists():
                continue
                
            # Check if new profile already exists
            if not NewProfile.objects.filter(user_id=user_id).exists():
                NewProfile.objects.create(
                    user_id=user_id,
                    role=role,
                    tenant_id=tenant_id
                )

class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0021_client_telegram'),
    ]

    operations = [
        migrations.RunPython(migrate_user_profiles),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS users_app_userprofile CASCADE;",
            reverse_sql="-- cannot restore users_app_userprofile automatically"
        ),
    ]
