# Generated by Django 5.2.10 on 2026-01-30 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0022_clean_up_old_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('status', models.CharField(choices=[('NEW', 'Новое'), ('REVIEWED', 'Рассмотрено'), ('PLANNED', 'Запланировано'), ('IN_PROGRESS', 'В разработке'), ('COMPLETED', 'Завершено'), ('REJECTED', 'Отклонено')], default='NEW', max_length=20, verbose_name='Статус')),
                ('priority', models.IntegerField(default=0, verbose_name='Приоритет (0-10)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='Заметки администратора')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='customers.client')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Предложение пользователя',
                'verbose_name_plural': 'Предложения пользователей',
                'ordering': ['-created_at'],
            },
        ),
    ]
