# Generated by Django 5.2.9 on 2026-01-08 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_options_task_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название этапа')),
                ('duration_minutes', models.PositiveIntegerField(default=0, verbose_name='Длительность (мин)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершен')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='tasks.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Этап задачи',
                'verbose_name_plural': 'Этапы задачи',
                'ordering': ['order', 'id'],
            },
        ),
    ]
