# Generated by Django 5.2.9 on 2026-01-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_taskstage'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstage',
            name='is_worker_added',
            field=models.BooleanField(default=False, verbose_name='Добавлено сотрудником'),
        ),
        migrations.AddField(
            model_name='taskstage',
            name='status',
            field=models.CharField(choices=[('PENDING', 'В планах'), ('IN_PROGRESS', 'В работе'), ('COMPLETED', 'Завершен'), ('FAILED', 'Проблема')], default='PENDING', max_length=20, verbose_name='Статус этапа'),
        ),
    ]
