# Generated by Django 5.2.10 on 2026-01-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_taskstage_is_worker_added_taskstage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstage',
            name='duration_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Длительность (текст)'),
        ),
        migrations.AddField(
            model_name='taskstage',
            name='materials_info',
            field=models.JSONField(blank=True, default=list, verbose_name='Информация о материалах'),
        ),
        migrations.AddField(
            model_name='taskstage',
            name='position_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность исполнителя'),
        ),
    ]
