# Generated by Django 5.2.9 on 2026-01-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_taskstage_is_worker_added_taskstage_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskstage',
            name='duration_minutes',
        ),
        migrations.AddField(
            model_name='task',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата закрытия'),
        ),
        migrations.AddField(
            model_name='task',
            name='control_object',
            field=models.CharField(blank=True, help_text='ID продукта, документа или сотрудника', max_length=100, verbose_name='Объект контроля'),
        ),
        migrations.AddField(
            model_name='task',
            name='external_id',
            field=models.CharField(blank=True, help_text='Напр. QA-2026-001', max_length=50, null=True, unique=True, verbose_name='ID задачи'),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(1, '1 - Низкий'), (2, '2 - Ниже среднего'), (3, '3 - Средний'), (4, '4 - Высокий'), (5, '5 - Критический')], default=3, verbose_name='Приоритет'),
        ),
        migrations.AddField(
            model_name='task',
            name='process_type',
            field=models.CharField(choices=[('AUDIT', 'Аудит'), ('CONTROL', 'Контроль партии'), ('INSPECTION', 'Инспекция'), ('REVIEW', 'Ревью')], default='CONTROL', max_length=20, verbose_name='Тип процесса'),
        ),
        migrations.AddField(
            model_name='task',
            name='source',
            field=models.CharField(choices=[('PLANNED', 'Плановая проверка'), ('COMPLAINT', 'Жалоба клиента'), ('FAILURE', 'Сбой на линии')], default='PLANNED', max_length=20, verbose_name='Источник задачи'),
        ),
        migrations.AddField(
            model_name='taskstage',
            name='actual_duration',
            field=models.PositiveIntegerField(default=0, verbose_name='Факт. длит. (мин)'),
        ),
        migrations.AddField(
            model_name='taskstage',
            name='damage_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма ущерба'),
        ),
        migrations.AddField(
            model_name='taskstage',
            name='defect_criticality',
            field=models.CharField(choices=[('MINOR', 'Малозначимый'), ('SIGNIFICANT', 'Значимый'), ('CRITICAL', 'Критический')], default='MINOR', max_length=20, verbose_name='Критичность дефекта'),
        ),
        migrations.AddField(
            model_name='taskstage',
            name='end_timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время окончания'),
        ),
        migrations.AddField(
            model_name='taskstage',
            name='executor_role',
            field=models.CharField(choices=[('ADMIN', 'Администратор'), ('WORKER', 'Работник'), ('LAB_TECH', 'Лаборант'), ('INSPECTOR', 'Инспектор')], default='WORKER', max_length=20, verbose_name='Роль исполнителя'),
        ),
        migrations.AddField(
            model_name='taskstage',
            name='planned_duration',
            field=models.PositiveIntegerField(default=0, verbose_name='План. длит. (мин)'),
        ),
        migrations.AddField(
            model_name='taskstage',
            name='reason_code',
            field=models.CharField(choices=[('NONE', 'Нет'), ('TEMP_ERR', 'Нарушение температурного режима'), ('TYPO', 'Опечатка'), ('BAD_PIXEL', 'Битый пиксель'), ('MATERIAL_DEFECT', 'Дефект материала'), ('HUMAN_FACTOR', 'Человеческий фактор')], default='NONE', max_length=20, verbose_name='Код отклонения'),
        ),
        migrations.AddField(
            model_name='taskstage',
            name='result_status',
            field=models.BooleanField(default=True, verbose_name='Результат (успех/брак)'),
        ),
        migrations.AddField(
            model_name='taskstage',
            name='start_timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Открыта'), ('PAUSE', 'Пауза'), ('CONTINUE', 'В работе'), ('IMPORTANT', 'Важно'), ('CLOSE', 'Закрыта')], default='OPEN', max_length=20, verbose_name='Статус'),
        ),
    ]
