# Generated by Django 5.2.9 on 2026-01-10 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_remove_taskstage_duration_minutes_task_closed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Напр. QC-MICRO-02', max_length=50, unique=True, verbose_name='Код шаблона')),
                ('title', models.CharField(max_length=200, verbose_name='Название процесса')),
                ('description', models.TextField(blank=True, verbose_name='Описание / Инструкция (Wiki)')),
                ('process_type', models.CharField(choices=[('AUDIT', 'Аудит'), ('CONTROL', 'Контроль партии'), ('INSPECTION', 'Инспекция'), ('REVIEW', 'Ревью')], default='CONTROL', max_length=20, verbose_name='Тип процесса')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Категория (напр. Автосервис, Электроника)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Шаблон задачи',
                'verbose_name_plural': 'Справочник процессов (Шаблоны)',
            },
        ),
        migrations.AlterField(
            model_name='task',
            name='source',
            field=models.CharField(choices=[('PLANNED', 'Плановая проверка'), ('COMPLAINT', 'Жалоба клиента'), ('FAILURE', 'Сбой на линии'), ('TEMPLATE', 'Из справочника (шаблон)')], default='PLANNED', max_length=20, verbose_name='Источник задачи'),
        ),
        migrations.AddField(
            model_name='task',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.tasktemplate', verbose_name='Шаблон процесса'),
        ),
        migrations.CreateModel(
            name='TaskTemplateStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название этапа')),
                ('executor_role', models.CharField(choices=[('ADMIN', 'Администратор'), ('WORKER', 'Работник'), ('LAB_TECH', 'Лаборант'), ('INSPECTOR', 'Инспектор')], default='WORKER', max_length=20, verbose_name='Роль исполнителя')),
                ('planned_duration', models.PositiveIntegerField(default=0, verbose_name='Норматив SLA (мин)')),
                ('data_type', models.CharField(choices=[('TEXT', 'Текст / Описание'), ('NUMBER', 'Числовое значение'), ('CHECKBOX', 'Pass / Fail (Чек-бокс)'), ('MEDIA', 'Медиаотчет (Фото/Видео)'), ('LIST', 'Список неисправностей')], default='TEXT', max_length=50, verbose_name='Тип данных для аналитики')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='tasks.tasktemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Этап шаблона',
                'verbose_name_plural': 'Этапы шаблона',
                'ordering': ['order', 'id'],
            },
        ),
    ]
