# Generated by Django 5.2.10 on 2026-01-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_taskstage_duration_text_taskstage_materials_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstage',
            name='position_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID должности (из public schema)'),
        ),
        migrations.AlterField(
            model_name='taskstage',
            name='position_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название должности'),
        ),
    ]
