# Generated by Django 5.2.10 on 2026-01-30 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_taskstage_position_id_alter_taskstage_position_name'),
        ('users_app', '0011_remove_tenantuser_can_delete_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='taskstage',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_assignments', to='users_app.tenantuser', verbose_name='Исполнитель'),
        ),
    ]
