# Generated by Django 5.2.9 on 2026-01-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_add_case_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstage',
            name='data_type',
            field=models.CharField(choices=[('TEXT', 'Текст / Описание'), ('NUMBER', 'Числовое значение'), ('CHECKBOX', 'Pass / Fail (Чек-бокс)'), ('MEDIA', 'Медиаотчет (Фото/Видео)'), ('LIST', 'Список неисправностей')], default='TEXT', max_length=50, verbose_name='Тип данных для аналитики'),
        ),
        migrations.AddField(
            model_name='taskstage',
            name='data_value',
            field=models.TextField(blank=True, help_text='Результат этапа (число, текст или JSON)', verbose_name='Значение данных'),
        ),
    ]
