# Generated by Django 5.2.10 on 2026-01-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_remove_task_assigned_to_taskstage_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstage',
            name='duration_unit',
            field=models.CharField(choices=[('second', 'Секунда'), ('minute', 'Минута'), ('hour', 'Час'), ('day', 'День')], default='minute', max_length=10, verbose_name='Единица времени'),
        ),
        migrations.AddField(
            model_name='taskstage',
            name='duration_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Длительность (значение)'),
        ),
        migrations.AlterField(
            model_name='taskstage',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='Длительность (мин, для совместимости)'),
        ),
    ]
