# Generated by Django 5.2.10 on 2026-01-30 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_taskstage_duration_unit_taskstage_duration_value_and_more'),
        ('users_app', '0011_remove_tenantuser_can_delete_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='users_app.tenantuser', verbose_name='Исполнитель'),
        ),
    ]
