# Generated by Django 5.2.9 on 2026-01-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_taskstage_data_type_taskstage_data_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktemplate',
            name='related_resource_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название ресурса'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='related_resource_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на ресурс (Wiki/Docs)'),
        ),
    ]
