# Generated by Django 5.2.10 on 2026-01-30 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_task_assigned_to'),
        ('users_app', '0011_remove_tenantuser_can_delete_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_tasks', to='users_app.tenantuser', verbose_name='Кто контролирует'),
        ),
    ]
