# Generated by Django 5.2.9 on 2026-01-11 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_update_case_templates_details'),
        ('users_app', '0011_remove_tenantuser_can_delete_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='actual_produced_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Фактически произведено (шт.)'),
        ),
        migrations.AddField(
            model_name='task',
            name='article_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Артикул / Децимальный номер'),
        ),
        migrations.AddField(
            model_name='task',
            name='bom_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID Спецификации (BOM)'),
        ),
        migrations.AddField(
            model_name='task',
            name='client_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заказчик (Клиент)'),
        ),
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Плановая дата выпуска'),
        ),
        migrations.AddField(
            model_name='task',
            name='deficit_list',
            field=models.TextField(blank=True, verbose_name='Список дефицита'),
        ),
        migrations.AddField(
            model_name='task',
            name='finished_goods_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата сдачи на склад ГП'),
        ),
        migrations.AddField(
            model_name='task',
            name='firmware_version',
            field=models.CharField(blank=True, max_length=50, verbose_name='Версия прошивки'),
        ),
        migrations.AddField(
            model_name='task',
            name='kit_received_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата получения комплектующих'),
        ),
        migrations.AddField(
            model_name='task',
            name='kit_status',
            field=models.CharField(choices=[('FULL', 'Полная'), ('PARTIAL', 'Частичная')], default='FULL', max_length=20, verbose_name='Статус комплектации'),
        ),
        migrations.AddField(
            model_name='task',
            name='leftover_components',
            field=models.TextField(blank=True, verbose_name='Остатки компонентов'),
        ),
        migrations.AddField(
            model_name='task',
            name='panel_type',
            field=models.CharField(blank=True, help_text='Одиночная или мультиблок', max_length=100, verbose_name='Вид панели'),
        ),
        migrations.AddField(
            model_name='task',
            name='pcb_revision',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ревизия (Версия) PCB'),
        ),
        migrations.AddField(
            model_name='task',
            name='product_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Наименование изделия'),
        ),
        migrations.AddField(
            model_name='task',
            name='project_files_url',
            field=models.URLField(blank=True, verbose_name='Файлы проекта (Gerber, P&P)'),
        ),
        migrations.AddField(
            model_name='task',
            name='quality_defects',
            field=models.TextField(blank=True, verbose_name='Выявленные дефекты'),
        ),
        migrations.AddField(
            model_name='task',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество к производству (шт.)'),
        ),
        migrations.AddField(
            model_name='task',
            name='repair_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество на ремонт'),
        ),
        migrations.AddField(
            model_name='task',
            name='scrap_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество брака (Scrap)'),
        ),
        migrations.AddField(
            model_name='task',
            name='stencil_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID Трафарета'),
        ),
        migrations.AddField(
            model_name='task',
            name='transfer_note_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Накладная на перемещение'),
        ),
        migrations.AddField(
            model_name='taskstage',
            name='assigned_executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_stages', to='users_app.tenantuser', verbose_name='Назначенный сотрудник'),
        ),
        migrations.AddField(
            model_name='taskstage',
            name='equipment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Рабочее место (Оборудование)'),
        ),
        migrations.AddField(
            model_name='taskstage',
            name='quantity_good',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во (Годных)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, verbose_name='Особые отметки / Описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='external_id',
            field=models.CharField(blank=True, help_text='Напр. PRD-2024-00123', max_length=50, null=True, unique=True, verbose_name='ID заказа'),
        ),
    ]
