# Generated by Django 5.2.9 on 2026-01-11 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_task_actual_produced_quantity_task_article_number_and_more'),
        ('users_app', '0011_remove_tenantuser_can_delete_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_tasks', to='users_app.tenantuser', verbose_name='Ответственный менеджер'),
        ),
        migrations.AddField(
            model_name='task',
            name='production_manager_signed',
            field=models.BooleanField(default=False, verbose_name='Подпись Начальника производства'),
        ),
        migrations.AddField(
            model_name='task',
            name='production_manager_signed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата подписи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Низкий'), (2, 'Нормальный'), (3, 'Срочный'), (4, 'Горит')], default=3, verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='task',
            name='process_type',
            field=models.CharField(choices=[('AUDIT', 'Аудит'), ('CONTROL', 'Контроль партии'), ('INSPECTION', 'Инспекция'), ('REVIEW', 'Ревью'), ('PRODUCTION', 'Заказ на производство')], default='CONTROL', max_length=20, verbose_name='Тип процесса'),
        ),
        migrations.AlterField(
            model_name='tasktemplate',
            name='process_type',
            field=models.CharField(choices=[('AUDIT', 'Аудит'), ('CONTROL', 'Контроль партии'), ('INSPECTION', 'Инспекция'), ('REVIEW', 'Ревью'), ('PRODUCTION', 'Заказ на производство')], default='CONTROL', max_length=20, verbose_name='Тип процесса'),
        ),
    ]
