# Generated by Django 5.2.10 on 2026-01-30 21:47

from django.db import migrations


def remove_control_object_field(apps, schema_editor):
    """Удаляем поле control_object из таблицы tasks_task если оно существует"""
    with schema_editor.connection.cursor() as cursor:
        # Проверяем, существует ли поле
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='tasks_task' 
            AND column_name='control_object'
        """)
        
        if cursor.fetchone():
            # Поле существует, удаляем его
            cursor.execute("ALTER TABLE tasks_task DROP COLUMN IF EXISTS control_object CASCADE")


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_task_supervisor'),
    ]

    operations = [
        migrations.RunPython(remove_control_object_field, reverse_code=migrations.RunPython.noop),
    ]
