# Generated by Django 5.2.10 on 2026-01-30 22:00

from django.db import migrations


def remove_priority_field(apps, schema_editor):
    """Удаляем поле priority из таблицы tasks_task если оно существует"""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='tasks_task' 
            AND column_name='priority'
        """)
        
        if cursor.fetchone():
            cursor.execute("ALTER TABLE tasks_task DROP COLUMN IF EXISTS priority CASCADE")


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_remove_control_object'),
    ]

    operations = [
        migrations.RunPython(remove_priority_field, reverse_code=migrations.RunPython.noop),
    ]
