# Generated by Django 5.2.10 on 2026-01-30 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_remove_control_object'),
        ('tasks', '0013_remove_priority'),
    ]

    operations = [
    ]
