# Generated by Django 5.2.9 on 2026-01-11 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_task_manager_task_production_manager_signed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100, unique=True, verbose_name='Номер заказа')),
                ('client_name', models.CharField(max_length=255, verbose_name='Заказчик')),
                ('date', models.DateField(verbose_name='Дата заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Справочник заказов',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название операции')),
                ('description', models.TextField(blank=True, verbose_name='Описание операции')),
                ('default_duration', models.PositiveIntegerField(default=0, verbose_name='Норматив SLA (мин)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Справочник операций',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('article', models.CharField(max_length=100, unique=True, verbose_name='Артикул')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Изделие',
                'verbose_name_plural': 'Справочник изделий',
            },
        ),
        migrations.CreateModel(
            name='TransferNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, unique=True, verbose_name='Номер накладной')),
                ('date', models.DateField(verbose_name='Дата накладной')),
                ('description', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Накладная',
                'verbose_name_plural': 'Справочник накладных',
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='Код спецификации')),
                ('version', models.CharField(blank=True, max_length=50, verbose_name='Версия')),
                ('file_url', models.URLField(blank=True, verbose_name='Ссылка на файлы')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='tasks.product', verbose_name='Изделие')),
            ],
            options={
                'verbose_name': 'Спецификация',
                'verbose_name_plural': 'Справочник спецификаций',
            },
        ),
    ]
