# Generated by Django 5.2.9 on 2026-01-11 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_clientorder_operation_product_transfernote_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operation',
            options={'verbose_name': 'Шаблон этапа', 'verbose_name_plural': 'Шаблоны этапов'},
        ),
        migrations.AddField(
            model_name='operation',
            name='data_type',
            field=models.CharField(choices=[('TEXT', 'Текст / Описание'), ('NUMBER', 'Числовое значение'), ('CHECKBOX', 'Pass / Fail (Чек-бокс)'), ('MEDIA', 'Медиаотчет (Фото/Видео)'), ('LIST', 'Список неисправностей')], default='TEXT', max_length=50, verbose_name='Тип данных'),
        ),
        migrations.AddField(
            model_name='operation',
            name='executor_role',
            field=models.CharField(choices=[('ADMIN', 'Администратор'), ('WORKER', 'Работник'), ('LAB_TECH', 'Лаборант'), ('INSPECTOR', 'Инспектор')], default='WORKER', max_length=20, verbose_name='Роль исполнителя'),
        ),
    ]
