# Generated by Django 5.2.9 on 2026-01-08 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0002_media_uploaded_by_alter_media_file'),
        ('tasks', '0002_task_assigned_to_task_is_completed_task_updated_at'),
        ('users_app', '0009_position_alter_tenantuser_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Медиа-файл', 'verbose_name_plural': 'Медиа-файлы'},
        ),
        migrations.AddField(
            model_name='media',
            name='recording_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Конец съемки'),
        ),
        migrations.AddField(
            model_name='media',
            name='recording_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало съемки'),
        ),
        migrations.AddField(
            model_name='media',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media', to='tasks.task', verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to='tenant_media/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='media',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='media',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки'),
        ),
        migrations.AlterField(
            model_name='media',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='users_app.tenantuser', verbose_name='Загрузил'),
        ),
    ]
