# Generated by Django 5.2.9 on 2026-01-08 16:09

import django.db.models.deletion
import media_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0003_alter_media_options_media_recording_end_and_more'),
        ('tasks', '0004_taskstage'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media', to='tasks.taskstage', verbose_name='Этап'),
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to=media_app.models.get_media_upload_path, verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='media',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название'),
        ),
    ]
