# Generated by Django 5.2.10 on 2026-01-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0004_media_stage_alter_media_file_alter_media_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='file_size',
            field=models.BigIntegerField(default=0, verbose_name='Размер файла (байты)'),
        ),
    ]
