# Generated by Django 5.2.9 on 2026-01-11 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0005_media_file_size'),
        ('tasks', '0012_task_actual_produced_quantity_task_article_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='tasks.taskstage', verbose_name='Этап'),
        ),
        migrations.AlterField(
            model_name='media',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='tasks.task', verbose_name='Задача'),
        ),
    ]
