# Generated by Django 5.2.9 on 2026-01-07 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_api_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='API Ключ')),
                ('active_model', models.CharField(choices=[('gpt-3.5-turbo', 'OpenAI GPT-3.5 Turbo (Экономичный)'), ('gpt-4-turbo', 'OpenAI GPT-4 Turbo (Платный, мощный)'), ('gpt-4o', 'OpenAI GPT-4o (Флагман)'), ('claude-3-haiku', 'Anthropic Claude 3 Haiku (Быстрый)'), ('claude-3-opus', 'Anthropic Claude 3 Opus (Платный, экспертный)'), ('gemini-1.5-pro', 'Google Gemini 1.5 Pro (Универсальный)'), ('mock', 'Демонстрационный режим (Без API-ключа)')], default='mock', max_length=50, verbose_name='Активная модель')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='AI включен')),
                ('temperature', models.FloatField(default=0.7, verbose_name='Температура (0.0 - 1.0)')),
                ('max_tokens', models.IntegerField(default=1000, verbose_name='Макс. токенов')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки AI',
                'verbose_name_plural': 'Настройки AI',
            },
        ),
    ]
