# Generated by Django 5.2.9 on 2026-01-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='api_base_url',
            field=models.URLField(blank=True, help_text='Например: https://api.deepseek.com', max_length=255, null=True, verbose_name='Base URL (для DeepSeek/OpenRouter)'),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='active_model',
            field=models.CharField(choices=[('gpt-3.5-turbo', 'OpenAI GPT-3.5 Turbo (Экономичный)'), ('gpt-4-turbo', 'OpenAI GPT-4 Turbo (Платный, мощный)'), ('gpt-4o', 'OpenAI GPT-4o (Флагман)'), ('claude-3-haiku', 'Anthropic Claude 3 Haiku (Быстрый)'), ('claude-3-opus', 'Anthropic Claude 3 Opus (Платный, экспертный)'), ('gemini-1.5-pro', 'Google Gemini 1.5 Pro (Универсальный)'), ('deepseek-v3.1', 'DeepSeek-V3.1 (Бесплатный, мощный)'), ('chat-z-ai', 'Z.AI Chat (Бесплатный)'), ('qwen-2.5', 'Alibaba Qwen 2.5 (Бесплатный, открытый)'), ('mock', 'Демонстрационный режим (Без API-ключа)')], default='mock', max_length=50, verbose_name='Активная модель'),
        ),
    ]
