# Generated by Django 5.2.9 on 2026-01-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0002_aisettings_api_base_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='anthropic_api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Anthropic API Key'),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='deepseek_api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='DeepSeek API Key'),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='gemini_api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Gemini API Key'),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='openai_api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='OpenAI API Key'),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='api_base_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Base URL'),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='provider_api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Активный API Ключ'),
        ),
    ]
