# Generated by Django 5.2.9 on 2026-01-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0003_aisettings_anthropic_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='anthropic_api_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Anthropic Base URL'),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='deepseek_api_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='DeepSeek/Other Base URL'),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='gemini_api_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Gemini Base URL'),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='openai_api_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='OpenAI Base URL'),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='api_base_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Base URL (общий)'),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='deepseek_api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='DeepSeek/Other API Key'),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='provider_api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ключ API (общий)'),
        ),
    ]
