# Generated by Django 5.2.9 on 2026-01-07 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0004_aisettings_anthropic_api_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aisettings',
            name='api_base_url',
        ),
        migrations.RemoveField(
            model_name='aisettings',
            name='provider_api_key',
        ),
    ]
