# Generated by Django 5.2.9 on 2026-01-07 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0005_remove_aisettings_api_base_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_code', models.CharField(max_length=50, unique=True, verbose_name='Код модели')),
                ('api_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='API Ключ')),
                ('api_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Base URL')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Конфигурация модели AI',
                'verbose_name_plural': 'Конфигурации моделей AI',
            },
        ),
        migrations.RemoveField(
            model_name='aisettings',
            name='anthropic_api_key',
        ),
        migrations.RemoveField(
            model_name='aisettings',
            name='anthropic_api_url',
        ),
        migrations.RemoveField(
            model_name='aisettings',
            name='deepseek_api_key',
        ),
        migrations.RemoveField(
            model_name='aisettings',
            name='deepseek_api_url',
        ),
        migrations.RemoveField(
            model_name='aisettings',
            name='gemini_api_key',
        ),
        migrations.RemoveField(
            model_name='aisettings',
            name='gemini_api_url',
        ),
        migrations.RemoveField(
            model_name='aisettings',
            name='openai_api_key',
        ),
        migrations.RemoveField(
            model_name='aisettings',
            name='openai_api_url',
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='active_model',
            field=models.CharField(choices=[('mock', 'Эмуляция (без API)'), ('gpt-3.5-turbo', 'OpenAI GPT-3.5 Turbo'), ('gpt-4', 'OpenAI GPT-4'), ('gpt-4o', 'OpenAI GPT-4o (рекомендуется)'), ('claude-3-haiku-20240307', 'Anthropic Claude 3 Haiku'), ('claude-3-opus-20240229', 'Anthropic Claude 3 Opus'), ('gemini-1.5-pro', 'Google Gemini 1.5 Pro'), ('deepseek-v3.1', 'DeepSeek-V3.1 (Free)'), ('chat-z-ai', 'Z.AI (DeepSeek-V3)'), ('qwen-2.5', 'Alibaba Qwen-2.5')], default='mock', max_length=50, verbose_name='Активная модель'),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='temperature',
            field=models.FloatField(default=0.7, verbose_name='Температура'),
        ),
    ]
