# Generated by Django 5.2.9 on 2026-01-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0006_aimodelconfig_remove_aisettings_anthropic_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aisettings',
            name='active_model',
            field=models.CharField(choices=[('mock', 'Эмуляция (без API)'), ('gpt-3.5-turbo', 'OpenAI GPT-3.5 Turbo'), ('gpt-4', 'OpenAI GPT-4'), ('gpt-4o', 'OpenAI GPT-4o (рекомендуется)'), ('claude-3-haiku-20240307', 'Anthropic Claude 3 Haiku'), ('claude-3-opus-20240229', 'Anthropic Claude 3 Opus'), ('gemini-1.5-pro', 'Google Gemini 1.5 Pro'), ('deepseek-v3.1', 'DeepSeek-V3.1 (Free)'), ('deepseek-3.2', 'DeepSeek-V3.2'), ('chat-z-ai', 'Z.AI (DeepSeek-V3)'), ('qwen-2.5', 'Alibaba Qwen-2.5')], default='mock', max_length=50, verbose_name='Активная модель'),
        ),
    ]
